/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface CallReceiverMockInterface extends ethers.utils.Interface {
  functions: {
    "mockFunction()": FunctionFragment;
    "mockFunctionNonPayable()": FunctionFragment;
    "mockFunctionOutOfGas()": FunctionFragment;
    "mockFunctionRevertsNoReason()": FunctionFragment;
    "mockFunctionRevertsReason()": FunctionFragment;
    "mockFunctionThrows()": FunctionFragment;
    "mockFunctionWritesStorage()": FunctionFragment;
    "mockStaticFunction()": FunctionFragment;
    "sharedAnswer()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "mockFunction",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mockFunctionNonPayable",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mockFunctionOutOfGas",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mockFunctionRevertsNoReason",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mockFunctionRevertsReason",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mockFunctionThrows",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mockFunctionWritesStorage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mockStaticFunction",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sharedAnswer",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "mockFunction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mockFunctionNonPayable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mockFunctionOutOfGas",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mockFunctionRevertsNoReason",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mockFunctionRevertsReason",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mockFunctionThrows",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mockFunctionWritesStorage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mockStaticFunction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sharedAnswer",
    data: BytesLike
  ): Result;

  events: {
    "MockFunctionCalled()": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "MockFunctionCalled"): EventFragment;
}

export class CallReceiverMock extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: CallReceiverMockInterface;

  functions: {
    mockFunction(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    mockFunctionNonPayable(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    mockFunctionOutOfGas(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    mockFunctionRevertsNoReason(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    mockFunctionRevertsReason(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    mockFunctionThrows(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    mockFunctionWritesStorage(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    mockStaticFunction(overrides?: CallOverrides): Promise<[string]>;

    sharedAnswer(overrides?: CallOverrides): Promise<[string]>;
  };

  mockFunction(
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  mockFunctionNonPayable(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  mockFunctionOutOfGas(
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  mockFunctionRevertsNoReason(
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  mockFunctionRevertsReason(
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  mockFunctionThrows(
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  mockFunctionWritesStorage(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  mockStaticFunction(overrides?: CallOverrides): Promise<string>;

  sharedAnswer(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    mockFunction(overrides?: CallOverrides): Promise<string>;

    mockFunctionNonPayable(overrides?: CallOverrides): Promise<string>;

    mockFunctionOutOfGas(overrides?: CallOverrides): Promise<void>;

    mockFunctionRevertsNoReason(overrides?: CallOverrides): Promise<void>;

    mockFunctionRevertsReason(overrides?: CallOverrides): Promise<void>;

    mockFunctionThrows(overrides?: CallOverrides): Promise<void>;

    mockFunctionWritesStorage(overrides?: CallOverrides): Promise<string>;

    mockStaticFunction(overrides?: CallOverrides): Promise<string>;

    sharedAnswer(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    MockFunctionCalled(): TypedEventFilter<[], {}>;
  };

  estimateGas: {
    mockFunction(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    mockFunctionNonPayable(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    mockFunctionOutOfGas(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    mockFunctionRevertsNoReason(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    mockFunctionRevertsReason(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    mockFunctionThrows(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    mockFunctionWritesStorage(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    mockStaticFunction(overrides?: CallOverrides): Promise<BigNumber>;

    sharedAnswer(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    mockFunction(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    mockFunctionNonPayable(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    mockFunctionOutOfGas(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    mockFunctionRevertsNoReason(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    mockFunctionRevertsReason(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    mockFunctionThrows(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    mockFunctionWritesStorage(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    mockStaticFunction(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    sharedAnswer(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
