/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface StringsMockInterface extends ethers.utils.Interface {
  functions: {
    "fromUint256(uint256)": FunctionFragment;
    "fromUint256Hex(uint256)": FunctionFragment;
    "fromUint256HexFixed(uint256,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "fromUint256",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fromUint256Hex",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fromUint256HexFixed",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "fromUint256",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fromUint256Hex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fromUint256HexFixed",
    data: BytesLike
  ): Result;

  events: {};
}

export class StringsMock extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: StringsMockInterface;

  functions: {
    fromUint256(
      value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    fromUint256Hex(
      value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    fromUint256HexFixed(
      value: BigNumberish,
      length: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  fromUint256(value: BigNumberish, overrides?: CallOverrides): Promise<string>;

  fromUint256Hex(
    value: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  fromUint256HexFixed(
    value: BigNumberish,
    length: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    fromUint256(
      value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    fromUint256Hex(
      value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    fromUint256HexFixed(
      value: BigNumberish,
      length: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    fromUint256(
      value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    fromUint256Hex(
      value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    fromUint256HexFixed(
      value: BigNumberish,
      length: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    fromUint256(
      value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    fromUint256Hex(
      value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    fromUint256HexFixed(
      value: BigNumberish,
      length: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
