/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  ClashingImplementation,
  ClashingImplementationInterface,
} from "../ClashingImplementation";

const _abi = [
  {
    inputs: [],
    name: "admin",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "delegatedFunction",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610154806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c8063abf8e0e71461003b578063f851a44014610059575b600080fd5b610043610077565b60405161005091906100c5565b60405180910390f35b610061610080565b60405161006e91906100aa565b60405180910390f35b60006001905090565b60006311111142905090565b610095816100e0565b82525050565b6100a4816100f2565b82525050565b60006020820190506100bf600083018461008c565b92915050565b60006020820190506100da600083018461009b565b92915050565b60006100eb826100fe565b9050919050565b60008115159050919050565b600073ffffffffffffffffffffffffffffffffffffffff8216905091905056fea2646970667358221220762b4f30766a30a3deeb2b81257adbb19380b7f92cb87d648607823719dec71264736f6c63430008000033";

export class ClashingImplementation__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ClashingImplementation> {
    return super.deploy(overrides || {}) as Promise<ClashingImplementation>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): ClashingImplementation {
    return super.attach(address) as ClashingImplementation;
  }
  connect(signer: Signer): ClashingImplementation__factory {
    return super.connect(signer) as ClashingImplementation__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ClashingImplementationInterface {
    return new utils.Interface(_abi) as ClashingImplementationInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ClashingImplementation {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ClashingImplementation;
  }
}
