/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  Implementation4,
  Implementation4Interface,
} from "../Implementation4";

const _abi = [
  {
    stateMutability: "nonpayable",
    type: "fallback",
  },
  {
    inputs: [],
    name: "getValue",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_number",
        type: "uint256",
      },
    ],
    name: "setValue",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506102d6806100206000396000f3fe608060405234801561001057600080fd5b50600436106100455760003560e01c8063209652551461004f578063552410771461006d5780638129fc1c1461008957610046565b5b60018081905550005b610057610093565b6040516100649190610253565b60405180910390f35b61008760048036038101906100829190610195565b61009d565b005b6100916100a7565b005b6000600154905090565b8060018190555050565b600060019054906101000a900460ff16806100cd575060008054906101000a900460ff16155b61010c576040517f08c379a000000000000000000000000000000000000000000000000000000000815260040161010390610233565b60405180910390fd5b60008060019054906101000a900460ff16159050801561015c576001600060016101000a81548160ff02191690831515021790555060016000806101000a81548160ff0219169083151502179055505b801561017d5760008060016101000a81548160ff0219169083151502179055505b50565b60008135905061018f81610289565b92915050565b6000602082840312156101a757600080fd5b60006101b584828501610180565b91505092915050565b60006101cb602e8361026e565b91507f496e697469616c697a61626c653a20636f6e747261637420697320616c72656160008301527f647920696e697469616c697a65640000000000000000000000000000000000006020830152604082019050919050565b61022d8161027f565b82525050565b6000602082019050818103600083015261024c816101be565b9050919050565b60006020820190506102686000830184610224565b92915050565b600082825260208201905092915050565b6000819050919050565b6102928161027f565b811461029d57600080fd5b5056fea26469706673582212202b6f2702ca3e546f9b5e025a0c15a2579d75219d6c09eadd9157856eb1f9ecbc64736f6c63430008000033";

export class Implementation4__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<Implementation4> {
    return super.deploy(overrides || {}) as Promise<Implementation4>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): Implementation4 {
    return super.attach(address) as Implementation4;
  }
  connect(signer: Signer): Implementation4__factory {
    return super.connect(signer) as Implementation4__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): Implementation4Interface {
    return new utils.Interface(_abi) as Implementation4Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Implementation4 {
    return new Contract(address, _abi, signerOrProvider) as Implementation4;
  }
}
