/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  ReentrancyAttack,
  ReentrancyAttackInterface,
} from "../ReentrancyAttack";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes4",
        name: "data",
        type: "bytes4",
      },
    ],
    name: "callSender",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610328806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c80630a2df1ed14610030575b600080fd5b61004a60048036038101906100459190610184565b61004c565b005b6000610056610167565b73ffffffffffffffffffffffffffffffffffffffff1682604051602401604051602081830303815290604052907bffffffffffffffffffffffffffffffffffffffffffffffffffffffff19166020820180517bffffffffffffffffffffffffffffffffffffffffffffffffffffffff83818316178352505050506040516100dd919061021e565b6000604051808303816000865af19150503d806000811461011a576040519150601f19603f3d011682016040523d82523d6000602084013e61011f565b606091505b5050905080610163576040517f08c379a000000000000000000000000000000000000000000000000000000000815260040161015a90610235565b60405180910390fd5b5050565b600033905090565b60008135905061017e816102db565b92915050565b60006020828403121561019657600080fd5b60006101a48482850161016f565b91505092915050565b60006101b882610255565b6101c28185610260565b93506101d28185602086016102a8565b80840191505092915050565b60006101eb601d8361026b565b91507f5265656e7472616e637941747461636b3a206661696c65642063616c6c0000006000830152602082019050919050565b600061022a82846101ad565b915081905092915050565b6000602082019050818103600083015261024e816101de565b9050919050565b600081519050919050565b600081905092915050565b600082825260208201905092915050565b60007fffffffff0000000000000000000000000000000000000000000000000000000082169050919050565b60005b838110156102c65780820151818401526020810190506102ab565b838111156102d5576000848401525b50505050565b6102e48161027c565b81146102ef57600080fd5b5056fea2646970667358221220bc2130ad9eab2d71615f4150ac821599f8e3bf08c3748873cc2d0ab1505a6d7264736f6c63430008000033";

export class ReentrancyAttack__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ReentrancyAttack> {
    return super.deploy(overrides || {}) as Promise<ReentrancyAttack>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): ReentrancyAttack {
    return super.attach(address) as ReentrancyAttack;
  }
  connect(signer: Signer): ReentrancyAttack__factory {
    return super.connect(signer) as ReentrancyAttack__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ReentrancyAttackInterface {
    return new utils.Interface(_abi) as ReentrancyAttackInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ReentrancyAttack {
    return new Contract(address, _abi, signerOrProvider) as ReentrancyAttack;
  }
}
