/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { SampleHuman, SampleHumanInterface } from "../SampleHuman";

const _abi = [
  {
    inputs: [],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "isHuman",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5061026d806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c80634a6c9db61461003b5780638129fc1c14610059575b600080fd5b610043610063565b60405161005091906101df565b60405180910390f35b610061610076565b005b600060029054906101000a900460ff1681565b600060019054906101000a900460ff168061009c575060008054906101000a900460ff16155b6100db576040517f08c379a00000000000000000000000000000000000000000000000000000000081526004016100d2906101fa565b60405180910390fd5b60008060019054906101000a900460ff16159050801561012b576001600060016101000a81548160ff02191690831515021790555060016000806101000a81548160ff0219169083151502179055505b6001600060026101000a81548160ff02191690831515021790555080156101675760008060016101000a81548160ff0219169083151502179055505b50565b6101738161022b565b82525050565b6000610186602e8361021a565b91507f496e697469616c697a61626c653a20636f6e747261637420697320616c72656160008301527f647920696e697469616c697a65640000000000000000000000000000000000006020830152604082019050919050565b60006020820190506101f4600083018461016a565b92915050565b6000602082019050818103600083015261021381610179565b9050919050565b600082825260208201905092915050565b6000811515905091905056fea26469706673582212205083f51dd2ab61836a0cb3ff91cbb8901418bc9c3295cdd8133fa60d0863777464736f6c63430008000033";

export class SampleHuman__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<SampleHuman> {
    return super.deploy(overrides || {}) as Promise<SampleHuman>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): SampleHuman {
    return super.attach(address) as SampleHuman;
  }
  connect(signer: Signer): SampleHuman__factory {
    return super.connect(signer) as SampleHuman__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): SampleHumanInterface {
    return new utils.Interface(_abi) as SampleHumanInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): SampleHuman {
    return new Contract(address, _abi, signerOrProvider) as SampleHuman;
  }
}
